import pygame

MOUSEPRESELECT = pygame.USEREVENT+2
MOUSESELECT = MOUSEPRESELECT+1
MOUSEENDSELECT = MOUSESELECT+1

HOTBARSELECTMOD = MOUSEENDSELECT+1
HOTBARINFOMOD = HOTBARSELECTMOD+1  # {'sprite': }
HOTBARMULTIINFOMOD = HOTBARINFOMOD+1  # {'sprites': }

HIGLIGHT = HOTBARMULTIINFOMOD+1
